# Generated by Django 5.0.7 on 2024-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedOpportunity',
            new_name='SavedOpportunities',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
        migrations.AlterField(
            model_name='volunteerpreferences',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='volunteerpreferences',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='volunteerpreferences',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
