# Generated by Django 5.0.7 on 2024-10-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_rename_savedopportunity_savedopportunities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='VolunteerApplication',
            new_name='VolunteerApplications',
        ),
    ]
