# Generated by Django 5.0.7 on 2024-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='user',
        ),
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
