# Generated by Django 5.0.7 on 2024-10-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_remove_organisation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='organsation_name',
            new_name='organisation_name',
        ),
    ]
