# Generated by Django 5.0.7 on 2024-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_remove_organisation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
