# Generated by Django 5.0.7 on 2024-10-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_organisation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='contact_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
