# Generated by Django 5.0.7 on 2024-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_alter_volunteeropportunity_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_opportunities',
            field=models.ManyToManyField(related_name='applied_by', through='volunteers.VolunteerApplications', to='volunteers.volunteeropportunity'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_opportunities',
            field=models.ManyToManyField(related_name='saved_by', through='volunteers.SavedOpportunities', to='volunteers.volunteeropportunity'),
        ),
    ]
