# Generated by Django 5.0.7 on 2024-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0017_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_is_private',
            field=models.BooleanField(default=False),
        ),
    ]
