# Generated by Django 5.0.7 on 2024-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0020_user_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
