# Generated by Django 5.0.7 on 2024-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0021_volunteeropportunity_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
