# Generated by Django 5.0.7 on 2025-01-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0022_alter_volunteeropportunity_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
